#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/holbertonscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

echo $$ > /var/run/myscript.pid

# function to clean up and exit
function cleanup_exit {
  rm /var/run/myscript.pid
  exit
}

# function to handle SIGTERM signal
function handle_sigterm {
  echo "I hate the kill command"
}

# function to handle SIGINT signal
function handle_sigint {
  echo "Y U no love me?!"
}

# set up signal handlers
trap 'cleanup_exit' SIGQUIT SIGTERM
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT

# display message indefinitely
echo "To infinity and beyond"
while true
do
  sleep 1
done

